### ISSUE TITLE
Bugfix for SetSlideshowShuffle

### ISSUE THREAD

**Issue by Kazenochi** [9eck0/IDesktopWallpaper-dotNet#1]
Hello I'm currently using this wrapper for a personal project and noticed that you can not change the Shuffle mode. After looking at the methode, I noticed that the parameter is not evaluated. I could be overlooking some reason for this but following is my fix if necessary.

        public void SetSlideshowShuffle(bool enable)
        {
            wallpaperEngine.GetSlideshowOptions(out uint _, out uint currentInterval);
            if(enable)
                wallpaperEngine.SetSlideshowOptions(1, currentInterval);
            else
                wallpaperEngine.SetSlideshowOptions(0, currentInterval);
        }

**Comment by warrenkc** [comment]
I created a pull request for this.
